// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['apiKey']!,
    appId: dotenv.env['appId']!,
    messagingSenderId: '710124233336',
    projectId: 'employees-coffee',
    authDomain: 'employees-coffee.firebaseapp.com',
    storageBucket: 'employees-coffee.appspot.com',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['apiKey']!,
    appId: dotenv.env['appId']!,
    messagingSenderId: '710124233336',
    projectId: 'employees-coffee',
    storageBucket: 'employees-coffee.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['apiKey']!,
    appId: dotenv.env['appId']!,
    messagingSenderId: '710124233336',
    projectId: 'employees-coffee',
    storageBucket: 'employees-coffee.appspot.com',
    iosClientId:
        '710124233336-4eai63po1k07jdjgo1dgq0g2vdvvjhqe.apps.googleusercontent.com',
    iosBundleId: 'com.example.employeesCoffeeFirestore',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['apiKey']!,
    appId: dotenv.env['appId']!,
    messagingSenderId: '710124233336',
    projectId: 'employees-coffee',
    storageBucket: 'employees-coffee.appspot.com',
    iosClientId:
        '710124233336-75c0vttb7b8b1731rbj2b86c6hke1mjr.apps.googleusercontent.com',
    iosBundleId: 'com.example.employeesCoffeeFirestore.RunnerTests',
  );
}
